
language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

install:
  - composer self-update

before-script:
  - composer install
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - phpunit -c app

notifications:
  email: ajimenez.bf@gmail.com