<?php

namespace AppBundle\Repository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{
    public function createQueryBuilderForTerms(array $terms, $alias = 'm')
    {
        $queryBuilder = $this->createQueryBuilder($alias);
        foreach ($terms as $key => $term) {
            $queryBuilder
                ->orWhere(sprintf('%s.title LIKE :t_%s', $alias, $key))
                ->setParameter('t_' . $key , '%' . $term . '%')
            ;
        }
        return $queryBuilder;
    }

    public function findAllMediasExceptTest()
    {
        $em  = $this->getEntityManager();
        $dql = 'SELECT m
                  FROM AppBundle:Media m
                 WHERE m.id > 1';

        $query = $em->createQuery($dql);
        $query->execute();
        return $query->getResult();
    }
}
