<?php

namespace AppBundle\Repository;

/**
 * mediaStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaStateRepository extends \Doctrine\ORM\EntityRepository
{
}
