<?php

namespace AppBundle\Repository;

/**
 * voteTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
