easy_admin:
    site_name: 'CPanel kveo'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    list:
        max_results: 20
    design:
        brand_color: '#BF0000'
    entities:
        Comment:
            class: AppBundle\Entity\Comment
            label: 'easy.comment.label'
            list:
                title: 'easy.comment.title'
                fields:
                    - 'id'
                    - { property: 'user', label: 'easy.user'}
                    - { property: 'media', label: 'easy.media'}
                    - { property: 'comment', label: 'easy.comment'}
                    - { property: 'publishedAt', label: 'easy.published'}
                    - { property: 'editedAt', label: 'easy.edited'}
        Media:
            class: AppBundle\Entity\Media
            label: 'easy.media.label'
            list:
                title: 'easy.media.title'
                fields:
                    - 'id'
                    - { property: 'title', label: 'easy.title'}
                    - { property: 'mediaType', label: 'easy.type'}
                    - { property: 'gender', label: 'easy.gender'}
                    - { property: 'image', type: 'image',  label: 'easy.image', base_path: %app.path.media_images% }
            form:
                fields:
                    - { property: 'title', label: 'easy.title'}
                    - { property: 'slug'}
                    - { property: 'imageFile', type: 'vich_image', label: 'easy.image' }
                    - { property: 'year', label: 'easy.year'}
                    - { property: 'plot', label: 'easy.plot'}
                    - { property: 'mediaType', label: 'easy.type'}
                    - { property: 'gender', label: 'easy.gender'}
                    - { property: 'trailer', label: 'easy.trailer'}
                    - { property: 'season', label: 'easy.season'}
                    - { property: 'persons', label: 'easy.person.label' }
        User:
             class: AppBundle\Entity\User
             label: 'easy.user.label'
             list:
                 title: 'easy.user.title'
                 fields:
                     - 'id'
                     - { property: 'username', label: 'easy.user'}
                     - { property: 'email', label: 'easy.email'}
                     - { property: 'locked', label: 'easy.locked'}
                     - { property: 'expired', label: 'easy.expired'}
                     - { property: 'roles', label: 'easy.roles'}
             form:
                fields:
                    - { property: 'username', label: 'easy.user'}
                    - { property: 'email', label: 'easy.email'}
                    - { property: 'password', label: 'easy.password'}
                    - { property: 'roles', label: 'easy.roles'}
                    - { property: 'enabled', label: 'easy.enabled'}
        Gender:
             class: AppBundle\Entity\Gender
             label: 'easy.gender.label'
             list:
                 title: 'easy.gender.title'
                 fields:
                     - 'id'
                     - { property: 'name', label: 'easy.gender'}
        MediaState:
             class: AppBundle\Entity\MediaState
             label: 'easy.media_state.label'
             list:
                 title: 'easy.media_state.title'
                 fields:
                     - 'id'
                     - { property: 'name', label: 'easy.state'}
        MediaType:
             class: AppBundle\Entity\MediaType
             label: 'easy.media_type.label'
             list:
                 title: 'easy.media_tipe.title'
                 fields:
                     - 'id'
                     - { property: 'name', label: 'easy.type'}
        Person:
             class: AppBundle\Entity\Person
             label: 'easy.person.label'
             list:
                 title: 'Actores'
                 fields:
                     - 'id'
                     - { property: 'name', label: 'easy.name'}
                     - { property: 'age', label: 'easy.age'}
                     - { property: 'birthplace', label: 'easy.birthplace'}
             form:
                fields:
                     - { property: 'name', label: 'easy.name'}
                     - { property: 'age', label: 'easy.age'}
                     - { property: 'birthplace', label: 'easy.birthplace'}
                     - { property: 'medias', label: 'easy.person.label'}
        State:
             class: AppBundle\Entity\State
             label: 'easy.state.label'
             list:
                 title: 'easy.person.title'
                 fields:
                     - 'id'
                     - { property: 'media', label: 'easy.media'}
                     - { property: 'user', label: 'easy.user'}
                     - { property: 'mediaState', label: 'easy.state'}
        Vote:
             class: AppBundle\Entity\Vote
             label: 'easy.vote.label'
             list:
                 title: 'easy.vote.title'
                 fields:
                     - 'id'
                     - { property: 'media', label: 'easy.media'}
                     - { property: 'user', label: 'easy.user'}
                     - { property: 'rating', label: 'easy.vote'}