fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User

    registration:
        form:
            type: app_user_registration

    from_email:
      address:     mecaigotolosdias@gmail.com
      sender_name: kveo

    resetting:
        email:
            template: email/FOSUserBundle.resetting.email.html.twig
