liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        media:
            filters:
                upscale: { min: [200, 220] }
                thumbnail: { size: [200, 220], mode: inset }
        bannerw:
            filters:
                upscale: { min: [1600, 160] }
                thumbnail: { size: [1600, 160], mode: inset}
        filmography:
            filters:
                upscale: { min: [150, 170] }
                thumbnail: { size: [150, 170], mode: inset}