parameters:
#    parameter_name: value

services:
    slugger:
        class: AppBundle\Utils\Slugger

    term_splitter:
        class: AppBundle\Utils\TermSplitter

    comment_voter:
        class: AppBundle\Security\CommentVoter
        arguments:
            - "@security.access.decision_manager"
        public: false
        tags:
            - { name: security.voter }

    kveo_mailer:
        class: AppBundle\Utils\Mailer
        arguments:
            - "@mailer"
            - "@templating"